Repository artsalliancemedia/thunderstorm-auth-library, pull requests merged in 2019-02, with the labels that each got.

#68 [fix] fixes issue #67: role update does not clean orphan permissions …
  Makefile
  requirements.txt
  setup.py
  test/test_datastore.py
  test/test_roles.py
  thunderstorm_auth/__init__.py
  thunderstorm_auth/datastore.py
  thunderstorm_auth/roles.py
Labels: PR: unreviewed

#69 [feature] Index on complex group association
  README.md
  thunderstorm_auth/__init__.py
  thunderstorm_auth/group.py
Labels: PR: reviewed-approved

#70 Jwk set format change
  test/conftest.py
  test/test_decoder.py
  thunderstorm_auth/__init__.py
  thunderstorm_auth/decoder.py
  thunderstorm_auth/utils.py
Labels: PR: unreviewed

#73 Relax version constraint
  requirements.txt
  thunderstorm_auth/__init__.py
Labels: release
